/*The main.jsx file serves as the entry point for the React application, it imports the necessary dependencies and renders the App component into the root DOM element, it uses StrictMode to help identify potential issues in the application during development, ensuring that the app adheres to best practices and is free of common pitfalls, providing a solid foundation for building a robust and maintainable movie explorer application.*/
//StrictMode is a tool for highlighting potential problems in an application, it activates additional checks and warnings for its descendants, it helps identify unsafe lifecycle methods, legacy API usage, and other potential issues in the application during development, ensuring that the app adheres to best practices and is free of common pitfalls, providing a solid foundation for building a robust and maintainable movie explorer application.
import { StrictMode } from 'react'
/*createRoot is a method from react-dom/client that creates a root for rendering the React application, it takes a DOM element as an argument and returns a root object that has a render method to render the React components into the specified DOM element, it is used to initialize the React application and attach it to the HTML document, allowing us to build and display our movie explorer application in the browser.*/
import { createRoot } from 'react-dom/client'
/*App component is the main root component of the project, it serves as the entry point for the application and defines the overall structure and routing of the app, it includes the Navbar component that is displayed on every page, and uses react-router-dom to define routes for the Home page and Movie Detail page, allowing users to navigate between different pages without refreshing the entire page, providing a smooth and seamless user experience in a single-page application. The App component is responsible for rendering the appropriate components based on the current URL, enabling users to explore different movies based on their interests and view detailed information about each movie when selected from the home page.*/
import App from './App.jsx'

/*createRoot(document.getElementById('root')).render() is used to render the App component into the root DOM element with the ID of 'root', it initializes the React application and attaches it to the HTML document, allowing us to build and display our movie explorer application in the browser. The App component is wrapped in StrictMode to help identify potential issues in the application during development, ensuring that the app adheres to best practices and is free of common pitfalls, providing a solid foundation for building a robust and maintainable movie explorer application.*/
createRoot(document.getElementById('root')).render(
  /*StrictMode is a tool for highlighting potential problems in an application, it activates additional checks and warnings for its descendants, it helps identify unsafe lifecycle methods, legacy API usage, and other potential issues in the application during development, ensuring that the app adheres to best practices and is free of common pitfalls, providing a solid foundation for building a robust and maintainable movie explorer application. The App component is wrapped in StrictMode to help identify potential issues in the application during development, ensuring that the app adheres to best practices and is free of common pitfalls, providing a solid foundation for building a robust and maintainable movie explorer application. The createRoot method initializes the React application and attaches it to the HTML document, allowing us to build and display our movie explorer application in the browser. The App component serves as the main root component of the project, defining the overall structure and routing of the app, enabling users to explore different movies based on their interests and view detailed information about each movie when selected from the home page.*/
  <StrictMode>
    <App />
  </StrictMode>,
)